### ISSUE TITLE
3X TODO list for release

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#129]
## Documentation

- [ ] A lot of it

## Assembler

- [ ] Core syntax & compilation
- [ ] Expression syntax & support

## Assembler - Optional

- [ ] Intelligent tab-completion similar to IntelliJ where using the same thing repetitively makes it more likely to appear near the top of suggestions - #10

## Core features

- [ ] Assembler
    - [ ] Support for serializing comments into class file - #124
- [ ] Moderate Android support
    - [ ] Not full support, at least on initial release. But flesh out some of the missing supported items like context menus not working.
- [ ] Search
    - [ ] Refactor to support android resources - #49
- [ ] Workspace
    - [ ] Resources
        - [ ] Allow zip parsing strategy to be passed in, instead of always using JVM value. For the UI module this preference should be stored in config. - #126
    - [ ] Call graph generation - #45
- [ ] Reimplement SSVM from refactor branch, start with simple cases and verify with test cases that slowly building up and combining does not introduce regressions.

## Core features - Optional

- [ ] Mapping
    - [ ] Correlation mapping. Taking one jar that is obfuscated *(naming convention only)* and another that is cleanly named, allow Recaf to detect similar structures between each file and apply the clean mappings to the obfuscated jar - #127
- [ ] Workspace
    - [ ] Resources
        - [ ] Metadata / tagging system for classes and files - #17
        - [ ] Attaching ZIP entry metadata to `Info` types when loaded from archives (jar/zip/etc) - #36 / #97
        - [ ] Export changes (On primary resource) as `.patch` file to changes can be automated - #111
    - [ ] Remote synchronization with other Recaf clients *(Or a generalized server setup)* - #44

## Plugin

- [ ] Intermediate API allowing for quickstarting plugin development.

## UI

 - [ ] Menu bar
     - [ ] File
         - [ ] Export decompilation - #109
 - [ ] Welcome panel
     - [ ] Resume last project *(Load first workspace in recent memory, do not show this if no recent items exist)*
     - [ ] Tips along the bottom (next/prev to scrub through tips)
         - [ ] Create list of short but useful info like *"lambdas get compiled into separate synthetic members"*, *"Use the assembler if you can't use the compiler"*, and *"Seeing red? You screwed something up."*
 - [x] Workspace tree
     - [ ] Show `Workspace` as tree model
          - [ ] `Workspace` acts as root node
          - [ ] `Resource` acts as each child to the root
               - [ ] Support for 'jar in jar' situations like Spring Boot -  #115
               - [ ] Support context actions when loaded from android resource *(APK)*
 - [ ] Content panel
     - [ ] Main view
         - [ ] Decompile
             - [ ] Recompile support
                 - [x] Automatic version target *(based on class file version)*
                 - [ ] Manual version target selection *(In config)* - #125
         - [ ] Hex
             - [ ] For classes, tree view of class file format (Partially complete)
     - [ ] Side panes
         - [ ] Information
             - [ ] Class version (modifiable)
             - [ ] Access flags (modifiable)
             - [ ] SourceFile (modifiable)
             - [ ] Kotlin meta-data (from annotation if available) - #119
 - [ ] Assembler panel
     - [ ] Support class-level assembling - #63
     - [ ] Middle clicking on a label reference in a control-flow instruction should center the line containing the label on the screen - #60
 - [ ] Credits panel - #116

**Important bug fixes**

- [ ] Package/folder deletion not consistently removing the package/folder root - #99
- [ ] Package/folder deletion of a single long path not consistently deleting the root - #95

## UI - Optional

- [ ] Documentation & Setup
    - [ ] First-time configuration setting based on what the user intends to use Recaf for - #13
        - [ ] Consider Eclipse's step-through for changing default settings based on a few simple questions. 
        - [ ] Potentially have keybind sets based on other programs *(Port keybinds from IDE's)*
    - [ ] In-application tutorials without need to open a browser - #12
        - [ ] Consider comparing to Eclipse's tutorial series and IntelliJ's 'Learn IDE features'
- [ ] Workspace tree
    - [ ] Distinctly mark classes when modifications exist - #121

- [ ] Search panel
    - [ ] Configurable
        - [ ] Text fields
            - [x] Contains
            - [x] Equals
            - [x] Starts with
            - [x] Ends with
            - [ ] Fuzzy (Maybe? Not sure if useful)
        - [ ] Numeric fields
            - [x] Equals
            - [ ] Greater
            - [ ] Greater or equal
            - [ ] Less or equal
    - [ ] Live search results
- [ ] Content panel
    - [ ] Main view
        - [ ] Other formats
            - [ ] PDF
            - [ ] HTML 
                - [ ] Inline rendering *(can be toggle-able, fall back to XML text highlight)*
                - [ ] HTML + XML block collapsing
            - [ ] Markdown 
                - [ ] Inline rendering *(can be toggle-able, fall back to MD text highlight)*
            - [ ] More audio formats
            - [ ] Video formats
                - [ ] MP4
                - [ ] MOV?
- [ ] Assembler panel
    - [ ] Reference guide in assembler tool tab - #57
- [ ] Context menus
    - [ ] Refactor context actions: Allow text replace of class/package/file/directory name in strings when an item is renamed - #6
    - [ ] Packages
        - [ ] Create new class in package - #93
    
- [ ] Plugins panel
    - [ ] Remote plugins management *(Optional since we need to hammer our implementing the 'backend' first)*
- [ ] Unreferenced class detection
    - [ ] Can show warning on class when it is not referenced anywhere
